# Detect the OS and configure the build settings
ifeq ($(OS),Windows_NT)
    SEPARATOR = ;
else
    SEPARATOR = :
endif

# Configure the Java classpath
CLASSPATH = ${java.class.path}

# Compile the shared library
build:
	javac -classpath "$(CLASSPATH)" ${problemName}.java ${problemName}Provider.java
	jar cf ${problemName}.jar *.class META-INF

clean:
	rm -f *.class *.jar
	
run:
	java -classpath "$(CLASSPATH)" Example.java
