language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Re2bKdtYouljVxJCHgciSTrQW8e9QyPyKf+1j1rJ389FYDYJVzHqBj/55Mm+NsKsn7qq+MKAkISHvq65NE/MbXRChBRNM6GOE3k+ukybt7dCBXpsJ13CUVQ5i16IYgop7cyVrQZDS5R8cxduXCThQNwXmENoROK1mQqxijOD9PV5N5l2VUv1dTBlo6RUikeF2PGULzztVe8ESfB0CAyiFiqBGaV49JSvdqYMUFtcWoFRSU0+PoH8ezIG7OabhLL1cFj2KM9Bwrk4vO4JHQPRC2sCniT+O5m2CGkfASv2zzgBZNBsDvYTFLGfeqo2+UUEJrJG2jvpNBfcKjS4YU56k8WpQocnSmEWzBH+ZZhjbRtjqK2ZAyWYg4TDbGJwvNQysgjHmSLLBncVIXrMLrtzAtK0hGnWMuemKAL5AGBRN3a+M6g4p9FCPOqpMM1s+thzZslmeNKbLZsW4gOJCOW1H5+sKTRzM2l88kN1J0zjvNRc8OS7e4tCcDDl7T2Xl6GugVG0c5UHg4Mr4H43/Boe9A5rogLDppJLBo4c+Q38Y6iq/iso38BU2oK3AX1zOkH+c5easFYmE2JYZW/wiUEsDQClOQ3TFoRF2hLl0ORw+14LNLZ1x9OjMw3/W5UptKuvALxGmHqVst6OEwJrEXqnLM62IhX7R6nbU+BwZEZhhic="

addons:
  coverity_scan:
    project:
      name: "MOEAFramework/MOEAFramework"
      description: "Build submitted via Travis CI"
    notification_email: admin@moeaframework.org
    build_command: "ant build-binary"
    branch_pattern: coverity_scan

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

script:
  - ant -DON_TRAVIS=true -f test.xml
