# Detect the OS and configure the build settings
ifeq ($(OS),Windows_NT)
    SEPARATOR = ;
else
    SEPARATOR = :
endif

# Configure the Java classpath
CLASSPATH = ${java.class.path}

# Compile the external program
build:
	javac -classpath "$(CLASSPATH)" ${problemName}.java ${problemName}Provider.java
	jar cf ${problemName}.jar ${problemName}.py *.class META-INF

clean:
	rm -f $(LIBNAME) ${problemName}.o
	
run:
	java -classpath "$(CLASSPATH)" Example.java
