# Configure the platform-specific settings
ifeq ($(OS),Windows_NT)
    SEPARATOR := ;
else
    SEPARATOR := :
endif

CLASSPATH := ${java.class.path}

# Compile the external program
build:
	javac -classpath "$(CLASSPATH)" ${problemName}.java ${problemName}Provider.java
	jar cf ${problemName}.jar ${problemName}.py *.class META-INF
	rm -f *.class

clean:
	rm -f ${problemName}.jar
	
run:
	java -classpath "$(CLASSPATH)" Example.java
