/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moeaframework_problem_BBOB2016_CocoJNI */

#ifndef _Included_org_moeaframework_problem_BBOB2016_CocoJNI
#define _Included_org_moeaframework_problem_BBOB2016_CocoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoSetLogLevel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoSetLogLevel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoGetObserver
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoGetObserver
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoFinalizeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoFinalizeObserver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoGetSuite
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoGetSuite
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoFinalizeSuite
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoFinalizeSuite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoGetNextProblem
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoGetNextProblem
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoEvaluateFunction
 * Signature: (J[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoEvaluateFunction
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoEvaluateConstraint
 * Signature: (J[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoEvaluateConstraint
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetDimension
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetDimension
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetNumberOfObjectives
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetNumberOfObjectives
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetNumberOfConstraints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetNumberOfConstraints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetSmallestValuesOfInterest
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetSmallestValuesOfInterest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetLargestValuesOfInterest
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetLargestValuesOfInterest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_moeaframework_problem_BBOB2016_CocoJNI
 * Method:    cocoProblemGetIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_moeaframework_problem_BBOB2016_CocoJNI_cocoProblemGetIndex
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
