/* Copyright 2009-2024 David Hadka
 *
 * This file is part of the MOEA Framework.
 *
 * The MOEA Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * The MOEA Framework is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with the MOEA Framework.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Package for the Real-World Constrained Multi-Objective Problems (RWMOP) test problems
 * used in the CEC 2021 competition.
 * <p>
 * Test cases can be generated by running the following from Matlab or Octave:
 * <pre>
 *   output_precision(7)
 *   instance=5
 *   [f,g,h]=CEC2021_func(Cal_par(instance).xmin, instance)
 *   [f,g,h]=CEC2021_func(Cal_par(instance).xmax, instance)
 * </pre>
 * and converting any negative inequality constraint values ({@code g}) to {@code 0.0}.
 * <p>
 * References:
 * <ol>
 *   <li>Abhishek Kumar, Guohua Wu, Mostafa Ali, Qizhang Luo, Rammohan Mallipeddi, Ponnuthurai Suganthan,
 *       Swagatam Das. "A Benchmark-Suite of Real-World Constrained Multi-Objective Optimization Problems and some
 *       Baseline Results." CEC-2021, Krakow, Poland, 28 June - 01 July 2021.
 *   <li>https://github.com/P-N-Suganthan/2021-RW-MOP
 * </ol>
 */
package org.moeaframework.problem.RWMOP;