name: Native Image

on:
  push:
  workflow_dispatch:

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13 ]
    steps:
    - uses: actions/checkout@v4
    - name: Download and Install Java Native Image Kit (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        curl -s "https://get.sdkman.io" | bash
        source ~/.sdkman/bin/sdkman-init.sh
        sdk install java 24.2.1.r24-nik
        for child_dir in $(find "$HOME/.sdkman/candidates" -mindepth 1 -maxdepth 1 -type d); do
          echo "$child_dir/current/bin" >> $GITHUB_PATH
        done
    - name: Download Java Native Image Kit (Windows)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        curl -L -o java-24.2.1.zip https://api.sdkman.io/2/broker/download/java/24.2.1.r24-nik/$(uname)
    - name: Install Java Native Image Kit (Windows)
      uses: actions/setup-java@v4
      if: runner.os == 'Windows'
      with:
        distribution: 'jdkfile'
        java-version: 24.2.1
        jdkFile: java-24.2.1.zip
    - name: Build native image
      shell: bash
      run: |
        ant build-native
    - name: Timing
      shell: bash
      run: |
        echo "Compiled:"
        time build/cli Solve --algorithm NSGAII --problem UF1 --numberOfEvaluations 1000000 --output output.txt
        echo "Java:"
        time java --class-path "lib/*${{ runner.os == 'Windows' && ';' || ':' }}dist/*" org.moeaframework.analysis.tools.Main Solve --algorithm NSGAII --problem UF1 --numberOfEvaluations 1000000 --output output.txt
    - name: Upload native image
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: native-image-${{ matrix.os }}
        path: build/
