name: Native Image

on:
  push:
  workflow_dispatch:

jobs:
  native-image-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Java Native Image Kit
      run: |
        curl -s "https://get.sdkman.io" | bash
        source ~/.sdkman/bin/sdkman-init.sh
        sdk install java 24.2.1.r24-nik
    - name: Build native image
      run: |
        ant update-reachability
        ant build-binary
        native-image --no-fallback -classpath "dist/*:lib/*" org.moeaframework.analysis.tools.Main -o cli
    - name: Test native image
      run: |
        ./cli Solve --algorithm NSGAII --problem UF1 --numberOfEvaluations 10000 --output output.txt
    - name: Upload native image
      uses: actions/upload-artifact@v4
      with:
        name: native-image-ubuntu
        path: |
          cli
          META-INF/native-image/reachability-metadata.json
        
  native-image-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Java Native Image Kit
      shell: bash
      run: |
        uname
        curl -L -o java-24.2.1.zip https://api.sdkman.io/2/broker/download/java/24.2.1.r24-nik/$(uname)
    - uses: actions/setup-java@v4
      with:
        distribution: 'jdkfile'
        java-version: 24.2.1
        jdkFile: java-24.2.1.zip
    - name: Build native image
      run: |
        ant update-reachability
        ant build-binary
        native-image --no-fallback -classpath "dist/*;lib/*" org.moeaframework.analysis.tools.Main -o cli.exe
    - name: Test native image
      run: |
        cli.exe Solve --algorithm NSGAII --problem UF1 --numberOfEvaluations 10000 --output output.txt
    - name: Upload native image
      uses: actions/upload-artifact@v4
      with:
        name: native-image-windows
        path: |
          cli.exe
          META-INF/native-image/reachability-metadata.json
